import { createContext, useContext } from 'react'

export const LangContext = createContext(null)

export const STRINGS = {
  en: {
    appName: 'Dog near me',
    tagline: "Report a stray dog you spotted — see if someone's already named it",
    navMap: 'Map',
    navReport: 'Report a dog',

    signIn: 'Sign in',
    signInWithGoogle: 'Continue with Google',
    signOut: 'Sign out',
    signInRequired: 'Sign in to report a dog — browsing the map is open to everyone.',
    signInBlurb: 'Sign in so your reports are credited and you can edit dogs you added.',

    mapLocate: 'Find my location',
    mapLocateStop: 'Stop tracking',
    mapLocateDenied: 'Location permission denied',
    mapLocateError: "Couldn't find your location",
    mapLocateUnsupported: 'Geolocation not supported',
    mapEmptyHint: 'No dogs reported near here yet — be the first!',
    mapLoadingHint: 'Loading nearby dogs…',
    mapSearchPlaceholder: 'Search by name or breed…',
    mapSearchNoResults: 'No dogs match that search',

    onboardingTitle: 'Welcome to Dog near me',
    onboardingBody: "Spot a stray dog? Snap a photo and report it — we'll check if the community already knows this dog by comparing photos and location, before you add a new one.",
    onboardingDismiss: 'Got it',

    installTitle: 'Install Dog near me for quick access',
    installButton: 'Install',
    installIosHint: 'Tap Share, then "Add to Home Screen"',

    reportTitle: 'Report a dog',
    reportTakePhoto: 'Take or choose a photo',
    reportRetake: 'Choose a different photo',
    reportGettingLocation: 'Getting your location…',
    reportLocationDenied: 'Location permission denied — we need it to match nearby dogs.',
    reportLocationError: "Couldn't get your location",
    reportUploading: 'Uploading photo…',
    reportAnalyzing: 'Looking at the photo…',
    reportUploadError: 'Something went wrong uploading that photo — try again.',
    reportRetryUpload: 'Retry upload',
    reportSearching: 'Checking for dogs already reported nearby…',
    reportCandidatesTitle: 'Is this one of these dogs?',
    reportCandidatesHint: 'Found {n} dog(s) reported near this spot',
    reportComparing: 'Comparing with nearby dogs…',
    reportLikelyMatch: 'Likely match',
    reportPossibleMatch: 'Possible match',
    reportSameDog: 'Yes, same dog',
    reportNoCandidates: 'No dogs reported near here yet',
    reportNotListed: "None of these — it's a new dog",
    reportNameLabel: 'Give this dog a name',
    reportNamePlaceholder: 'e.g. Somchai, Brownie, Sunny',
    reportNoteLabel: 'Note (optional)',
    reportNotePlaceholder: 'Anything worth mentioning — injured, skittish, hangs out near a shop…',
    reportConfirmReportingOf: 'Reporting a sighting of {name}',
    reportPossibleOwnerWarning: 'This dog appears to be wearing a collar — it may already have an owner.',
    friendlinessLabel: 'How friendly does this dog seem? (optional)',
    friendlinessFriendly: 'Friendly',
    friendlinessNeutral: 'Neutral / cautious',
    friendlinessCautious: 'Keep distance',
    reportAnonymousLabel: 'Report anonymously (hide my name from other users)',
    reportSubmit: 'Submit report',
    reportSubmitting: 'Saving…',
    reportSuccessNew: 'New dog added!',
    reportSuccessMatched: 'Sighting added to {name}',
    reportAnother: 'Report another',
    reportRateLimited: "You've hit today's report limit — try again tomorrow.",
    distanceAway: '{d}m away',

    dogUnnamed: 'Unnamed dog',
    dogLastSeen: 'Last seen',
    dogSightings: 'Sightings',
    dogReportSighting: 'Report another sighting of this dog',
    dogRename: 'Edit name',
    dogSave: 'Save',
    dogCancel: 'Cancel',
    dogClose: 'Close',
    dogShare: 'Share',
    dogShareLine: 'Share via LINE',
    dogShareText: 'Check out {name} on Dog near me',
    dogInfoAI: 'From photo analysis',
    dogInfoCommunity: 'Reported by the community',
    dogLinkCopied: 'Link copied',
    dogReportedBy: 'Reported by {name}',
    dogAnonymousReporter: 'Anonymous',
    dogMultipleReporters: 'Reported by {count} different people',
    dogPossibleOwner: 'May have an owner — wearing a collar',
    dogBreed: 'Likely breed',
    dogTemperament: 'Temperament',
    dogTemperamentNone: 'No temperament reports yet',
    dogTemperamentCount: '({count} of {total} reports)',
    dogDeleteSighting: 'Delete this report',
    dogDeleteConfirm: "Delete this report? This can't be undone.",
    dogDeleteFailed: "Couldn't delete that — try again.",
    dogMergeTitle: 'Merge with another dog',
    dogMergeHint: "Pick the dog this should be merged into. All sightings will move there and this entry will be removed — this can't be undone.",
    dogMergeSearchPlaceholder: 'Search by name or breed…',
    dogMergeNoResults: 'No matches',
    dogMergeConfirmQuestion: 'Merge into "{name}"? This can\'t be undone.',
    dogMergeConfirmButton: 'Merge',
    dogMergeFailed: "Couldn't merge — try again.",
    dogReport: 'Report this dog',
    dogReportHint: 'See something wrong — a bad photo, wrong info, or a duplicate? Flag it here for review.',
    dogReportReasonLabel: "What's wrong?",
    dogReportReasonPhoto: 'Inappropriate photo',
    dogReportReasonWrongInfo: 'Wrong information',
    dogReportReasonDuplicate: 'Duplicate entry',
    dogReportReasonOther: 'Other',
    dogReportNoteLabel: 'Note (optional)',
    dogReportNotePlaceholder: 'Anything that would help us review this',
    dogReportSubmit: 'Submit report',
    dogReportSuccess: "Thanks — we'll take a look.",
    dogReportFailed: "Couldn't submit — try again.",
    dogFlagsTitle: 'Flagged ({count})',
    dogFlagDismiss: 'Dismiss',
    dogFlagDeleteDog: 'Delete this dog',
    dogFlagDeleteConfirm: "Delete this dog and all its sightings? This can't be undone.",
    dogFlagDeleteFailed: "Couldn't delete — try again.",
  },
  th: {
    appName: 'หมาใกล้ฉัน',
    tagline: 'รายงานหมาจรที่เจอ — ดูว่ามีใครตั้งชื่อไว้แล้วหรือยัง',
    navMap: 'แผนที่',
    navReport: 'รายงานหมา',

    signIn: 'เข้าสู่ระบบ',
    signInWithGoogle: 'ดำเนินการต่อด้วย Google',
    signOut: 'ออกจากระบบ',
    signInRequired: 'เข้าสู่ระบบเพื่อรายงานหมา — ดูแผนที่ได้โดยไม่ต้องล็อกอิน',
    signInBlurb: 'เข้าสู่ระบบเพื่อให้รายงานของคุณมีชื่อผู้รายงาน และแก้ไขหมาที่คุณเพิ่มได้',

    mapLocate: 'ค้นหาตำแหน่งของฉัน',
    mapLocateStop: 'หยุดติดตามตำแหน่ง',
    mapLocateDenied: 'ไม่ได้รับอนุญาตให้เข้าถึงตำแหน่ง',
    mapLocateError: 'ค้นหาตำแหน่งไม่สำเร็จ',
    mapLocateUnsupported: 'อุปกรณ์ไม่รองรับ',
    mapEmptyHint: 'ยังไม่มีรายงานหมาแถวนี้ — เป็นคนแรกสิ!',
    mapLoadingHint: 'กำลังโหลดหมาแถวนี้…',
    mapSearchPlaceholder: 'ค้นหาด้วยชื่อหรือสายพันธุ์…',
    mapSearchNoResults: 'ไม่พบหมาที่ตรงกับคำค้นหา',

    onboardingTitle: 'ยินดีต้อนรับสู่หมาใกล้ฉัน',
    onboardingBody: 'เจอหมาจรใช่ไหม? ถ่ายรูปแล้วรายงานเลย — เราจะเช็กก่อนว่าชุมชนเคยรู้จักหมาตัวนี้แล้วหรือยัง โดยเทียบรูปและตำแหน่ง ก่อนเพิ่มเป็นหมาตัวใหม่',
    onboardingDismiss: 'เข้าใจแล้ว',

    installTitle: 'ติดตั้งแอปหมาใกล้ฉันเพื่อเข้าใช้งานเร็วขึ้น',
    installButton: 'ติดตั้ง',
    installIosHint: 'แตะปุ่มแชร์ แล้วเลือก "เพิ่มไปยังหน้าจอโฮม"',

    reportTitle: 'รายงานหมา',
    reportTakePhoto: 'ถ่ายหรือเลือกรูปภาพ',
    reportRetake: 'เลือกรูปอื่น',
    reportGettingLocation: 'กำลังหาตำแหน่งของคุณ…',
    reportLocationDenied: 'ไม่ได้รับอนุญาตให้เข้าถึงตำแหน่ง — จำเป็นต้องใช้เพื่อจับคู่หมาใกล้เคียง',
    reportLocationError: 'หาตำแหน่งไม่สำเร็จ',
    reportUploading: 'กำลังอัปโหลดรูป…',
    reportAnalyzing: 'กำลังดูรูปภาพ…',
    reportUploadError: 'อัปโหลดรูปไม่สำเร็จ ลองใหม่อีกครั้ง',
    reportRetryUpload: 'ลองอัปโหลดใหม่',
    reportSearching: 'กำลังตรวจสอบหมาที่เคยรายงานแถวนี้…',
    reportCandidatesTitle: 'ใช่หมาตัวนี้หรือเปล่า?',
    reportCandidatesHint: 'พบหมา {n} ตัวที่เคยรายงานแถวนี้',
    reportComparing: 'กำลังเปรียบเทียบกับหมาที่อยู่ใกล้เคียง…',
    reportLikelyMatch: 'น่าจะใช่ตัวนี้',
    reportPossibleMatch: 'อาจจะใช่ตัวนี้',
    reportSameDog: 'ใช่ หมาตัวนี้แหละ',
    reportNoCandidates: 'ยังไม่มีหมาที่รายงานแถวนี้',
    reportNotListed: 'ไม่ใช่ตัวไหนเลย — เป็นหมาตัวใหม่',
    reportNameLabel: 'ตั้งชื่อหมาตัวนี้',
    reportNamePlaceholder: 'เช่น สมชาย บราวนี่ ซันนี่',
    reportNoteLabel: 'หมายเหตุ (ไม่บังคับ)',
    reportNotePlaceholder: 'สิ่งที่ควรบอก — บาดเจ็บ ขี้ตกใจ อยู่แถวร้านค้า…',
    reportConfirmReportingOf: 'กำลังรายงานการพบเห็น {name}',
    reportPossibleOwnerWarning: 'หมาตัวนี้ดูเหมือนใส่ปลอกคอ — อาจมีเจ้าของแล้ว',
    friendlinessLabel: 'หมาตัวนี้เป็นมิตรแค่ไหน? (ไม่บังคับ)',
    friendlinessFriendly: 'เป็นมิตร',
    friendlinessNeutral: 'เฉยๆ / ระวังตัว',
    friendlinessCautious: 'ควรเว้นระยะห่าง',
    reportAnonymousLabel: 'รายงานแบบไม่เปิดเผยชื่อ (ซ่อนชื่อจากผู้ใช้คนอื่น)',
    reportSubmit: 'ส่งรายงาน',
    reportSubmitting: 'กำลังบันทึก…',
    reportSuccessNew: 'เพิ่มหมาตัวใหม่แล้ว!',
    reportSuccessMatched: 'เพิ่มการพบเห็นให้ {name} แล้ว',
    reportAnother: 'รายงานอีกครั้ง',
    reportRateLimited: 'คุณรายงานครบโควตาวันนี้แล้ว ลองใหม่พรุ่งนี้',
    distanceAway: 'ห่าง {d} เมตร',

    dogUnnamed: 'หมาไม่มีชื่อ',
    dogLastSeen: 'พบล่าสุด',
    dogSightings: 'ครั้งที่พบเห็น',
    dogReportSighting: 'รายงานการพบเห็นหมาตัวนี้อีกครั้ง',
    dogRename: 'แก้ไขชื่อ',
    dogSave: 'บันทึก',
    dogCancel: 'ยกเลิก',
    dogClose: 'ปิด',
    dogShare: 'แชร์',
    dogShareLine: 'แชร์ใน LINE',
    dogShareText: 'มาดู {name} ใน หมาใกล้ฉัน',
    dogInfoAI: 'จากการวิเคราะห์รูปภาพ',
    dogInfoCommunity: 'รายงานโดยชุมชน',
    dogLinkCopied: 'คัดลอกลิงก์แล้ว',
    dogReportedBy: 'รายงานโดย {name}',
    dogAnonymousReporter: 'ไม่ระบุชื่อ',
    dogMultipleReporters: 'มีผู้รายงานแล้ว {count} คน',
    dogPossibleOwner: 'อาจมีเจ้าของ — ใส่ปลอกคออยู่',
    dogBreed: 'สายพันธุ์โดยประมาณ',
    dogTemperament: 'นิสัย',
    dogTemperamentNone: 'ยังไม่มีรายงานเรื่องนิสัย',
    dogTemperamentCount: '({count} จาก {total} รายงาน)',
    dogDeleteSighting: 'ลบรายงานนี้',
    dogDeleteConfirm: 'ลบรายงานนี้? ไม่สามารถย้อนกลับได้',
    dogDeleteFailed: 'ลบไม่สำเร็จ ลองใหม่อีกครั้ง',
    dogMergeTitle: 'รวมเข้ากับหมาตัวอื่น',
    dogMergeHint: 'เลือกหมาที่จะรวมเข้าด้วยกัน ประวัติการพบเห็นทั้งหมดจะย้ายไปที่นั่น และรายการนี้จะถูกลบ — ไม่สามารถย้อนกลับได้',
    dogMergeSearchPlaceholder: 'ค้นหาด้วยชื่อหรือสายพันธุ์…',
    dogMergeNoResults: 'ไม่พบรายการที่ตรงกัน',
    dogMergeConfirmQuestion: 'รวมเข้ากับ "{name}"? ไม่สามารถย้อนกลับได้',
    dogMergeConfirmButton: 'รวม',
    dogMergeFailed: 'รวมไม่สำเร็จ ลองใหม่อีกครั้ง',
    dogReport: 'รายงานหมาตัวนี้',
    dogReportHint: 'เจอปัญหาไหม — รูปไม่เหมาะสม ข้อมูลผิด หรือรายการซ้ำ? แจ้งได้ที่นี่',
    dogReportReasonLabel: 'มีปัญหาอะไร?',
    dogReportReasonPhoto: 'รูปภาพไม่เหมาะสม',
    dogReportReasonWrongInfo: 'ข้อมูลไม่ถูกต้อง',
    dogReportReasonDuplicate: 'รายการซ้ำ',
    dogReportReasonOther: 'อื่นๆ',
    dogReportNoteLabel: 'หมายเหตุ (ไม่บังคับ)',
    dogReportNotePlaceholder: 'สิ่งที่จะช่วยให้เราตรวจสอบได้',
    dogReportSubmit: 'ส่งรายงาน',
    dogReportSuccess: 'ขอบคุณ เราจะตรวจสอบให้',
    dogReportFailed: 'ส่งไม่สำเร็จ ลองใหม่อีกครั้ง',
    dogFlagsTitle: 'ถูกรายงาน ({count})',
    dogFlagDismiss: 'ยกเลิกรายงาน',
    dogFlagDeleteDog: 'ลบหมาตัวนี้',
    dogFlagDeleteConfirm: 'ลบหมาตัวนี้พร้อมประวัติการพบเห็นทั้งหมด? ไม่สามารถย้อนกลับได้',
    dogFlagDeleteFailed: 'ลบไม่สำเร็จ ลองใหม่อีกครั้ง',
  },
}

export function useLangContext() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLangContext must be used within LangContext.Provider')
  return ctx
}

// Simple {placeholder} interpolation, matching the rest of the monorepo's apps.
export function interp(template, vars) {
  if (typeof template !== 'string') return ''
  return Object.entries(vars || {}).reduce(
    (s, [k, v]) => s.replaceAll(`{${k}}`, String(v)),
    template,
  )
}
