import { createContext, useContext, useState } from 'react'

export const LangContext = createContext(null)

export const STRINGS = {
  en: {
    appName: 'Bill Splitter',
    tabSplit: 'Split Bill',
    tabSushi: 'Sushiro',
    members: 'Members',
    addMember: '+ Add',
    memberPlaceholder: 'Name e.g. Ann, Tom',
    nameTaken: 'Name already exists',
    noMembers: 'No members yet — add names above',
    removeLabel: 'Remove',
    foodItems: 'Food items',
    addFood: '+ Add item',
    foodPlaceholder: 'Food name',
    noFoods: 'No items yet — tap "+ Add item" to start',
    whoEats: 'Who eats:',
    everyone: 'All',
    splitHint: 'per person',
    extrasTitle: 'Charges & Details',
    close: 'Close',
    edit: 'Edit',
    ppPlaceholder: 'Phone or ID number',
    copied: '✓ Copied',
    copy: 'Copy',
    notSet: 'Not set',
    bankLabel: 'Bank info',
    bankPlaceholder: 'e.g.\nBank ABC\nAcc no. 111-111111-1\nJohn Doe',
    notesLabel: 'Notes',
    notesPlaceholder: 'e.g. Ice cream paid separately',
    result: 'Summary',
    noData: 'Add members and food items to see the bill',
    share: 'Share ₗ',
    sharePrefix: '📋 Bill Summary',
    shareTotal: 'Total:',
    foodSubtotal: 'Food subtotal',
    serviceCharge: 'Service Charge',
    vat: 'VAT',
    total: 'Grand total',
    people: 'People',
    addPerson: '+ Add',
    personPlaceholder: 'Name e.g. Pum, Gigi',
    platesOf: 'Plates for',
    resetAll: 'Reset all',
    snacks: '🍟 Snacks / Others',
    snackName: 'Item name (optional)',
    snackPrice: 'Price',
    subtotalOf: 'Subtotal for',
    options: 'Options',
    summary: 'Per person summary',
    plates: 'plates',
    items: 'items',
    grandTotal: 'Grand total',
    addEmpty: 'Add people first, then count plates for each person',
    perPerson: 'per person',
    price: 'Price',
  },
  th: {  
    appName: 'หารถิล',
    tabSplit: 'หารถิล',
    tabSushi: 'Sushiro',
    members: 'สมา',
    addMember: '+ เพิ่ม',
    memberPlaceholder: 'ชื่อ เช่น แอน, บอม',
    nameTaken: 'ชื่อนี้มีแล้ว',
    noMembers: 'ยังครนรวมัจ — เพิ่มชื่อด้านบนก่อนเลย',
    removeLabel: 'ลย',
    foodItems: 'รายการอาหาร',
    addFood: '+ เพิ่มรายการ',   
    foodPlaceholder: 'ชื่อรายการ',
    noFoods: 'ยังไม่มีรายการ — กด"+ เพิ่มรายการ" เพื่อเริ่ม',
    whoEats: 'ใครกิน:',
    everyone: 'ทุกคน',
    splitHint: 'คนละ',
    extrasTitle: 'ค่าธฐรเนียม',
    close: 'ปิด',
    edit: 'แก้ไข',
    ppPlaceholder: 'เบอร์โทร หรือ เลขบัตรปรกชาชน',
    copied: '✓ คัดลอกแล้ว',
    copy: 'คัดลอก',
    notSet: 'ยังไม่ได้ตั้งค่�*',
    bankLabel: 'ข้อมูลธนาคธร',
    bankPlaceholder: 'เช่น\nธนาคธร ABC\nเลขที่บัญชี 111-111111-1\nนายสุขใจดี',
    notesLabel: 'โน้ต',
    notesPlaceholder: 'หมายเหตุ เช่น ค่าน้ำแข็ง',
    result: 'สรุปบิล',
    noData: 'เพิ่มสมารายการอาหารและรายบิล',
    share: 'แชร์ให้เพื่อน ↗',
    sharePrefix: '📋 สรุปบิล',
    shareTotal: 'รวม:',
    foodSubtotal: 'ยอดอาหาร',
    serviceCharge: 'Service Charge',
    vat: 'VAT',
    total: 'รวมทั้งหมด',
    people: 'คนที่กิน',
    addPerson: '+ เพิ่ม',
    personPlaceholder: 'ชื่อ เช่น พุม, กีกี้',
    platesOf: 'จานของ',
    resetAll: 'รีเซ็ตทุกคน',
    snacks: '🍟 ของกินเล่น / อื่นๆ',
    snackName: 'ชื่อรายการ (ไม่บังคับ)',
    snackPrice: 'ราคา',
    subtotalOf: 'รวมของ',
    options: 'ตัวเลือก',
    summary: 'สรุปรายคน',
    plates: 'จาน',
    items: 'รายการ',
    grandTotal: 'รวมทั้งหมด',
    addEmpty: 'เพิ่มชื่อคนก่อน แล้วค่อยนับจานให้แต่ละคน',
    perPerson: 'คนละ',
    price: 'ราคา',
  },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = STRINGS[lang]
  const toggle = () => setLang(l => l === 'th' ? 'en' : 'th')
  return (
    <LangContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
