import { createContext, useContext, useEffect, useState } from 'react'

export const LangContext = createContext(null)

export const STRINGS = {
  en: {
    appName: 'Stock Ranges',
    tagline: 'See where each stock sits in its own recent price range.',
    backToHome: 'Back to portfolio',
    addPlaceholder: 'Ticker, e.g. AAPL',
    addBtn: 'Add',
    lookbackLabel: 'Lookback',
    range1d: '1 day',
    range7d: '7 days',
    range3mo: '3 months',
    range6mo: '6 months',
    range1y: '1 year',
    range2y: '2 years',
    range5y: '5 years',
    sortByLabel: 'Sort',
    sortSignal: 'Signal',
    sortChange: 'Day change',
    sortValue: 'Market value',
    sortPL: 'P/L %',
    sortAlpha: 'Alphabetical',
    sortYield: 'Dividend yield',
    emptyWatchlist: 'No tickers yet — add one above to see its price range.',
    noTagMatches: 'No tickers match the selected tags.',
    noSearchMatches: 'No matches for your search.',
    noFilterMatches: 'No tickers match the selected filters.',
    searchPlaceholder: 'Search symbol…',
    searchClear: 'Clear search',
    filterByTag: 'Filter',
    addTag: 'Tag',
    addTagPlaceholder: 'Tag name',
    removeTag: 'Remove tag',
    duplicateTagError: 'This ticker already has that tag.',
    maxTagsError: 'Maximum 8 tags per ticker.',
    manageTagsTitle: 'Manage tags',
    manageTagsBody: 'Rename or delete a tag everywhere it’s used, across both Watchlist and Wallet.',
    renameTagLabel: 'Rename tag',
    deleteTagLabel: 'Delete tag',
    tagUsageLabel: 'Used by {n}',
    closeBtn: 'Close',
    undoRemoved: 'Removed {symbol}',
    undoRemovedTag: 'Removed tag "{tag}"',
    undoBtn: 'Undo',
    navWatchlist: 'Watchlist',
    navWallet: 'Wallet',
    walletEmpty: 'No holdings yet — add one below to track it.',
    walletLockedTitle: 'Sign in to use Wallet',
    walletLockedBody: 'Wallet holdings sync across your devices, so they need an account. Watchlist still works without signing in.',
    summaryCostBasis: 'Cost basis',
    summaryMarketValue: 'Market value',
    summaryUnrealizedPL: 'Unrealized P/L',
    addHoldingBtn: '+ Add holding',
    qtyLabel: 'Quantity',
    avgCostLabel: 'Avg. cost',
    costCurrencyLabel: 'Currency',
    saveHoldingBtn: 'Save',
    invalidQtyError: 'Enter a quantity greater than 0.',
    invalidCostError: 'Enter a valid average cost (0 or more).',
    editHoldingLabel: 'Edit holding',
    cancelBtn: 'Cancel',
    removeHoldingLabel: 'Remove holding',
    currentPriceLabel: 'Current price',
    dividendSectionTitle: 'Dividend income',
    estPerMonth: 'Est. dividend/mo',
    estPerQuarter: 'Est. dividend/qtr',
    trailingTwelveMonth: 'Trailing 12mo',
    dividendYieldLabel: 'Yield',
    noDividendHistory: 'No dividend history in the last 2 years.',
    dividendCalendarTitle: 'Dividend calendar',
    dividendEstimatedTag: 'Estimated',
    showHistory: 'Show history',
    hideHistory: 'Hide history',
    importFromPdfBtn: 'Import from PDF',
    importModalTitle: 'Import holdings from PDF',
    importReadingPage: 'Reading page {page} of {total}…',
    importExtracting: 'Extracting holdings…',
    importEmptyResult: 'No holdings table found in this PDF.',
    importColSymbol: 'Symbol',
    importSelectAll: 'Select/deselect all',
    importConfirmBtn: 'Import {n} holdings',
    importSkippedRows: "Couldn't import {n} row(s) — check symbol, quantity, and cost: {symbols}",
    importErrorRateLimit: 'Too many imports recently — try again in a bit.',
    importErrorNetwork: 'Network error — could not reach the import service.',
    importErrorService: 'Import service error — try again.',
    importErrorConfig: 'Import service is not configured.',
    groupCommonStock: 'Common Stock',
    groupETF: 'ETF',
    groupOther: 'Other',
    historyTitle: 'Portfolio value',
    historyBuilding: 'History builds up as you visit — check back tomorrow for a trend.',
    historyRange7d: '7D',
    historyRange30d: '30D',
    historyRange90d: '90D',
    historyRangeAll: 'All',
    allocationTitle: 'Allocation',
    allocationShowMore: 'Show {n} more',
    allocationShowLess: 'Show less',
    maskShow: 'Show amounts',
    maskHide: 'Hide amounts',
    shareBtn: 'Share summary as image',
    shareError: "Couldn't create the share image — try again.",
    low: 'Low',
    high: 'High',
    band: 'Band',
    signalBuy: 'Buy zone',
    signalHold: 'Hold',
    signalSell: 'Sell zone',
    signalFlat: 'Not enough range',
    loading: 'Loading…',
    errorPrefix: 'Error: ',
    retry: 'Retry',
    quoteErrorNotFound: 'Ticker not found.',
    quoteErrorNetwork: 'Network error — could not reach the quote service.',
    quoteErrorService: 'Quote service error — try again.',
    quoteErrorConfig: 'Quote service is not configured.',
    removeLabel: 'Remove',
    duplicateTicker: 'Already in your watchlist',
    invalidTickerFormat: 'Not a valid ticker format.',
    updatedJustNow: 'Updated just now',
    updatedPrefix: 'Updated',
    updatedMinSuffix: 'm ago',
    currencyToggle: 'Switch between USD and THB',
    langToggle: 'Switch language',
    themeToggleLight: 'Switch to light mode',
    themeToggleDark: 'Switch to dark mode',
    chartTypeSwitchToCandle: 'Switch to candlestick view',
    chartTypeSwitchToLine: 'Switch to line view',
    refreshBtn: 'Refresh prices',
    ownedBadgeTitle: 'You own this — view in Wallet',
    watchedBadgeTitle: 'On your watchlist — view',
    fxUnavailable: 'Exchange rate unavailable — showing native currency',
    disclaimerTitle: 'Not financial advice',
    disclaimer: 'The band and buy/hold/sell label are a simple statistical measure of where today’s price sits within its own recent range — nothing more. They say nothing about a company’s fundamentals or future performance. Do your own research before making any investment decision.',
    acctSignIn: 'Sign in',
    acctContinueWithGoogle: 'Continue with Google',
    acctSigningIn: 'Signing in…',
    acctSignOut: 'Sign out',
    acctSyncing: 'Syncing…',
    acctSynced: 'Synced',
    acctSyncError: 'Sync error',
    acctSyncBlurb: 'Sign in to sync your watchlist across devices.',
    acctSignInError: 'Sign-in failed — try again.',
    conflictTitle: 'Watchlist differs on another device',
    conflictBody: 'This account already has a synced watchlist that doesn’t match this device. Pick which one to keep — the other will be replaced.',
    conflictThisDevice: 'This device',
    conflictOtherDevice: 'Other device',
    conflictTickerCount: '{n} tickers',
    conflictLastSaved: 'Last saved {when}',
    conflictNeverSaved: 'Not saved yet',
    conflictUse: 'Use this',
  },
  th: {
    appName: 'ช่วงราคาหุ้น',
    tagline: 'ดูว่าราคาหุ้นแต่ละตัวอยู่ตรงไหนในช่วงราคาล่าสุดของมันเอง',
    backToHome: 'กลับสู่หน้ารวมแอป',
    addPlaceholder: 'สัญลักษณ์หุ้น เช่น AAPL',
    addBtn: 'เพิ่ม',
    lookbackLabel: 'ช่วงเวลาย้อนหลัง',
    range1d: '1 วัน',
    range7d: '7 วัน',
    range3mo: '3 เดือน',
    range6mo: '6 เดือน',
    range1y: '1 ปี',
    range2y: '2 ปี',
    range5y: '5 ปี',
    sortByLabel: 'เรียงตาม',
    sortSignal: 'สัญญาณ',
    sortChange: 'เปลี่ยนแปลงวันนี้',
    sortValue: 'มูลค่าตลาด',
    sortPL: 'กำไร/ขาดทุน %',
    sortAlpha: 'ตามตัวอักษร',
    sortYield: 'อัตราเงินปันผล',
    emptyWatchlist: 'ยังไม่มีหุ้นในรายการ — เพิ่มด้านบนเพื่อดูช่วงราคา',
    noTagMatches: 'ไม่มีหุ้นที่ตรงกับแท็กที่เลือก',
    noSearchMatches: 'ไม่พบรายการที่ตรงกับคำค้นหา',
    noFilterMatches: 'ไม่มีหุ้นที่ตรงกับตัวกรองที่เลือก',
    searchPlaceholder: 'ค้นหาสัญลักษณ์…',
    searchClear: 'ล้างคำค้นหา',
    filterByTag: 'กรอง',
    addTag: 'แท็ก',
    addTagPlaceholder: 'ชื่อแท็ก',
    removeTag: 'ลบแท็ก',
    duplicateTagError: 'หุ้นตัวนี้มีแท็กนี้อยู่แล้ว',
    maxTagsError: 'ใส่แท็กได้สูงสุด 8 รายการต่อหุ้นหนึ่งตัว',
    manageTagsTitle: 'จัดการแท็ก',
    manageTagsBody: 'เปลี่ยนชื่อหรือลบแท็กในทุกที่ที่ใช้งาน ทั้งในรายการเฝ้าดูและพอร์ต',
    renameTagLabel: 'เปลี่ยนชื่อแท็ก',
    deleteTagLabel: 'ลบแท็ก',
    tagUsageLabel: 'ใช้กับ {n} รายการ',
    closeBtn: 'ปิด',
    undoRemoved: 'ลบ {symbol} แล้ว',
    undoRemovedTag: 'ลบแท็ก "{tag}" แล้ว',
    undoBtn: 'เลิกทำ',
    navWatchlist: 'รายการเฝ้าดู',
    navWallet: 'พอร์ต',
    walletEmpty: 'ยังไม่มีการถือครอง — เพิ่มด้านล่างเพื่อเริ่มติดตาม',
    walletLockedTitle: 'เข้าสู่ระบบเพื่อใช้พอร์ต',
    walletLockedBody: 'ข้อมูลพอร์ตจะซิงค์ข้ามอุปกรณ์ จึงต้องมีบัญชีผู้ใช้ ส่วนรายการเฝ้าดูยังใช้ได้โดยไม่ต้องเข้าสู่ระบบ',
    summaryCostBasis: 'ต้นทุนรวม',
    summaryMarketValue: 'มูลค่าตลาด',
    summaryUnrealizedPL: 'กำไร/ขาดทุน (ยังไม่รับรู้)',
    addHoldingBtn: '+ เพิ่มการถือครอง',
    qtyLabel: 'จำนวน',
    avgCostLabel: 'ราคาต้นทุนเฉลี่ย',
    costCurrencyLabel: 'สกุลเงิน',
    saveHoldingBtn: 'บันทึก',
    invalidQtyError: 'กรอกจำนวนที่มากกว่า 0',
    invalidCostError: 'กรอกราคาต้นทุนเฉลี่ยที่ถูกต้อง (0 ขึ้นไป)',
    editHoldingLabel: 'แก้ไขการถือครอง',
    cancelBtn: 'ยกเลิก',
    removeHoldingLabel: 'ลบการถือครอง',
    currentPriceLabel: 'ราคาปัจจุบัน',
    dividendSectionTitle: 'รายได้เงินปันผล',
    estPerMonth: 'ประมาณปันผล/เดือน',
    estPerQuarter: 'ประมาณปันผล/ไตรมาส',
    trailingTwelveMonth: '12 เดือนล่าสุด',
    dividendYieldLabel: 'อัตราเงินปันผล',
    noDividendHistory: 'ไม่มีประวัติเงินปันผลใน 2 ปีที่ผ่านมา',
    dividendCalendarTitle: 'ปฏิทินเงินปันผล',
    dividendEstimatedTag: 'ประมาณการ',
    showHistory: 'แสดงประวัติ',
    hideHistory: 'ซ่อนประวัติ',
    importFromPdfBtn: 'นำเข้าจาก PDF',
    importModalTitle: 'นำเข้าการถือครองจาก PDF',
    importReadingPage: 'กำลังอ่านหน้า {page} จาก {total}…',
    importExtracting: 'กำลังดึงข้อมูลการถือครอง…',
    importEmptyResult: 'ไม่พบตารางการถือครองใน PDF นี้',
    importColSymbol: 'สัญลักษณ์',
    importSelectAll: 'เลือก/ยกเลิกทั้งหมด',
    importConfirmBtn: 'นำเข้า {n} รายการ',
    importSkippedRows: 'นำเข้าไม่สำเร็จ {n} รายการ — ตรวจสอบสัญลักษณ์ จำนวน และราคาต้นทุน: {symbols}',
    importErrorRateLimit: 'นำเข้าบ่อยเกินไป — ลองใหม่อีกครั้งในอีกสักครู่',
    importErrorNetwork: 'เกิดข้อผิดพลาดเครือข่าย — ไม่สามารถเชื่อมต่อบริการนำเข้าได้',
    importErrorService: 'บริการนำเข้าขัดข้อง — ลองใหม่อีกครั้ง',
    importErrorConfig: 'ยังไม่ได้ตั้งค่าบริการนำเข้า',
    groupCommonStock: 'หุ้นสามัญ',
    groupETF: 'กองทุน ETF',
    groupOther: 'อื่น ๆ',
    historyTitle: 'มูลค่าพอร์ต',
    historyBuilding: 'ประวัติจะค่อยๆ สะสมทุกครั้งที่เข้ามาดู — กลับมาดูอีกครั้งพรุ่งนี้เพื่อดูแนวโน้ม',
    historyRange7d: '7 วัน',
    historyRange30d: '30 วัน',
    historyRange90d: '90 วัน',
    historyRangeAll: 'ทั้งหมด',
    allocationTitle: 'สัดส่วนการลงทุน',
    allocationShowMore: 'แสดงอีก {n} รายการ',
    allocationShowLess: 'แสดงน้อยลง',
    maskShow: 'แสดงจำนวนเงิน',
    maskHide: 'ซ่อนจำนวนเงิน',
    shareBtn: 'แชร์สรุปเป็นรูปภาพ',
    shareError: 'สร้างรูปภาพสำหรับแชร์ไม่สำเร็จ — ลองอีกครั้ง',
    low: 'ต่ำสุด',
    high: 'สูงสุด',
    band: 'ระดับ',
    signalBuy: 'โซนซื้อ',
    signalHold: 'ถือ',
    signalSell: 'โซนขาย',
    signalFlat: 'ข้อมูลไม่พอ',
    loading: 'กำลังโหลด…',
    errorPrefix: 'ผิดพลาด: ',
    retry: 'ลองอีกครั้ง',
    quoteErrorNotFound: 'ไม่พบสัญลักษณ์หุ้นนี้',
    quoteErrorNetwork: 'เกิดข้อผิดพลาดเครือข่าย — ไม่สามารถเชื่อมต่อบริการราคาหุ้นได้',
    quoteErrorService: 'บริการราคาหุ้นขัดข้อง — ลองใหม่อีกครั้ง',
    quoteErrorConfig: 'ยังไม่ได้ตั้งค่าบริการราคาหุ้น',
    removeLabel: 'ลบ',
    duplicateTicker: 'มีอยู่ในรายการแล้ว',
    invalidTickerFormat: 'รูปแบบสัญลักษณ์หุ้นไม่ถูกต้อง',
    updatedJustNow: 'อัปเดตล่าสุด',
    updatedPrefix: 'อัปเดตเมื่อ',
    updatedMinSuffix: ' นาทีที่แล้ว',
    currencyToggle: 'สลับระหว่าง USD และ THB',
    langToggle: 'เปลี่ยนภาษา',
    themeToggleLight: 'สลับเป็นโหมดสว่าง',
    themeToggleDark: 'สลับเป็นโหมดมืด',
    chartTypeSwitchToCandle: 'สลับเป็นกราฟแท่งเทียน',
    chartTypeSwitchToLine: 'สลับเป็นกราฟเส้น',
    refreshBtn: 'รีเฟรชราคา',
    ownedBadgeTitle: 'คุณถือครองหุ้นนี้ — ดูในพอร์ต',
    watchedBadgeTitle: 'อยู่ในรายการเฝ้าดู — ดู',
    fxUnavailable: 'ไม่สามารถแปลงสกุลเงินได้ — แสดงสกุลเงินต้นฉบับ',
    disclaimerTitle: 'ไม่ใช่คำแนะนำการลงทุน',
    disclaimer: 'ระดับและป้ายซื้อ/ถือ/ขาย เป็นเพียงการวัดทางสถิติง่ายๆ ว่าราคาปัจจุบันอยู่ตรงไหนในช่วงราคาล่าสุดของหุ้นนั้นเท่านั้น ไม่ได้บ่งบอกถึงพื้นฐานบริษัทหรือผลการดำเนินงานในอนาคต โปรดศึกษาข้อมูลเพิ่มเติมก่อนตัดสินใจลงทุน',
    acctSignIn: 'เข้าสู่ระบบ',
    acctContinueWithGoogle: 'ดำเนินการต่อด้วย Google',
    acctSigningIn: 'กำลังเข้าสู่ระบบ…',
    acctSignOut: 'ออกจากระบบ',
    acctSyncing: 'กำลังซิงค์…',
    acctSynced: 'ซิงค์แล้ว',
    acctSyncError: 'ซิงค์ผิดพลาด',
    acctSyncBlurb: 'เข้าสู่ระบบเพื่อซิงค์รายการหุ้นของคุณข้ามอุปกรณ์',
    acctSignInError: 'เข้าสู่ระบบไม่สำเร็จ — ลองอีกครั้ง',
    conflictTitle: 'รายการหุ้นไม่ตรงกับอุปกรณ์อื่น',
    conflictBody: 'บัญชีนี้มีรายการหุ้นที่ซิงค์ไว้แล้วซึ่งไม่ตรงกับอุปกรณ์นี้ เลือกว่าจะเก็บรายการไหนไว้ — อีกอันจะถูกแทนที่',
    conflictThisDevice: 'อุปกรณ์นี้',
    conflictOtherDevice: 'อุปกรณ์อื่น',
    conflictTickerCount: '{n} หุ้น',
    conflictLastSaved: 'บันทึกล่าสุด {when}',
    conflictNeverSaved: 'ยังไม่ได้บันทึก',
    conflictUse: 'ใช้อันนี้',
  },
}

const LANG_KEY = 'stockranges_lang'

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LANG_KEY) || 'th')

  useEffect(() => {
    localStorage.setItem(LANG_KEY, lang)
    document.documentElement.lang = lang
  }, [lang])

  const toggle = () => setLang((l) => (l === 'th' ? 'en' : 'th'))

  return (
    <LangContext.Provider value={{ lang, toggle, s: STRINGS[lang] }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
